PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(3,'2025_05_27_225405_create_demande_absences_table',1);
INSERT INTO migrations VALUES(4,'2025_05_27_230907_create_type_absences_table',1);
INSERT INTO migrations VALUES(5,'2025_05_29_222357_create_agents_table',1);
INSERT INTO migrations VALUES(6,'2025_05_30_084851_create_users_table',1);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
INSERT INTO cache VALUES('laravel_cache_aichaw2004icloud@gmail.com|127.0.0.1:timer','i:1748914150;',1748914150);
INSERT INTO cache VALUES('laravel_cache_aichaw2004icloud@gmail.com|127.0.0.1','i:1;',1748914150);
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "demande_absences" ("id" integer primary key autoincrement not null, "user_id" integer not null, "type_absence_id" integer not null, "date_debut" date not null, "date_fin" date not null, "description" text, "statut" varchar not null default 'en attente', "justificatif" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("type_absence_id") references "type_absences"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "types_absences" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "agents" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime, "prenom" varchar not null, "nom" varchar not null, "email" varchar not null, "role" varchar not null);
INSERT INTO agents VALUES(1,'2025-06-03 01:34:49','2025-06-05 10:59:21','Carla','MASSERATI','carlamasserati@icloud.com','super_admin');
INSERT INTO agents VALUES(2,'2025-06-03 08:54:23','2025-06-03 08:54:23','Nafissatou','MARE','marefinafe@gmail.com','agent');
INSERT INTO agents VALUES(3,'2025-06-03 10:33:22','2025-06-03 14:30:31','Momar','HANNE','momar@gmail.com','admin_sectoriel');
INSERT INTO agents VALUES(5,'2025-06-03 13:56:08','2025-06-03 13:56:08','Fatou Bintou Rassoul','WADE','bbfa@gmail.com','super_admin');
INSERT INTO agents VALUES(7,'2025-06-03 14:36:06','2025-06-03 14:36:06','Ibrahima','FALL','iboufall@gmail.com','directeur');
INSERT INTO agents VALUES(8,'2025-06-03 15:26:16','2025-06-05 09:18:50','El Hadj Malick','NDOYE','emndoye@minfinances.sn','chef_service');
INSERT INTO agents VALUES(11,'2025-06-05 10:59:40','2025-06-05 10:59:40','Ndoura','DIAGNE','ndoura@gmail.com','agent');
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Aicha','aichamb86@gmail.com',NULL,'$2y$12$WqdGlFMpwghNu76tfeBukeAvF4essxda5hsdz86U.6GD6hdKao37u','jKp4mH43v54qkoy9nId4m9lghFubsYRgTlPw3BQ7iPpW0heu9psNUray5o9H','2025-06-03 01:31:22','2025-06-03 01:31:22');
INSERT INTO sqlite_sequence VALUES('migrations',6);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('agents',11);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "types_absences_name_unique" on "types_absences" ("name");
CREATE UNIQUE INDEX "agents_email_unique" on "agents" ("email");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
COMMIT;
